[phases.setup]
nixPkgs = [
  "nodejs_20",
  "python3",
  "gcc",
  "gnumake",
  "pkg-config",
  "sqlite"
]

[phases.install]
cmds = [
  "npm ci --unsafe-perm"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "./docker-entrypoint.sh"

[variables]
NODE_ENV = "production"
NPM_CONFIG_LOGLEVEL = "error"
PATH = "/usr/local/bin:/usr/bin:/bin"