[phases.setup]
nixPkgs = [
  "nodejs_20",
  "python3",
  "gcc",
  "gnumake",
  "pkg-config",
  "sqlite"
]

[phases.install]
cmds = [
  "npm ci --unsafe-perm",
  "ln -sf /opt/claude-code/cli.js /usr/local/bin/claude",
  "chmod +x /usr/local/bin/claude"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "node server/index.js"

[variables]
NODE_ENV = "production"
NPM_CONFIG_LOGLEVEL = "error"
PATH = "/usr/local/bin:/usr/bin:/bin"