[phases.setup]
nixPkgs = [
  "nodejs_20",
  "python3",
  "gcc",
  "gnumake",
  "pkg-config",
  "sqlite",
  "bash",
  "busybox",
  "coreutils"
]
cmds = [
  "mkdir -p /bin",
  "ln -sf $(which bash) /bin/sh",
  "ln -sf $(which bash) /bin/bash",
  "useradd -m -s /bin/bash -u 1000 appuser || true",
  "mkdir -p /home/appuser/.claude",
  "cp -r /root/.claude/* /home/appuser/.claude/ 2>/dev/null || true",
  "chown -R appuser:appuser /home/appuser",
  "chown -R appuser:appuser /app || true",
  "chown -R appuser:appuser /opt/claude-code || true",
  "chmod -R 755 /opt/claude-code || true"
]

[phases.install]
cmds = [
  "npm ci --unsafe-perm"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "bash ./docker-entrypoint.sh"

[variables]
NODE_ENV = "production"
NPM_CONFIG_LOGLEVEL = "error"
PATH = "/usr/local/bin:/usr/bin:/bin"