[variables]
NODE_ENV = "production"
PORT = "3000"
NPM_CONFIG_LOGLEVEL = "error"

[phases.setup]
nixPkgs = [
  "nodejs_20",
  "python3",
  "gcc",
  "gnumake",
  "pkg-config",
  "sqlite",
  "git"
]

[phases.install]
cmds = [
  "npm ci --prefer-offline --no-audit --unsafe-perm",
  "npm install -g @anthropic-ai/claude-code@latest"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "node server/index.js"