[providers]
node = "20"

[phases.setup]
nixPkgs = [
  "python3",
  "gcc",
  "gnumake",
  "pkg-config",
  "sqlite"
]

[phases.install]
cmds = [
  "npm ci --unsafe-perm"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "node server/index.js"

[variables]
NODE_ENV = "production"
NPM_CONFIG_LOGLEVEL = "error"